name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Git Config
      run: |
        git config --global user.email "ci@noahgilmore.com"
        git config --global user.name "Automated Deployment"
    - name: NPM install
      run: npm install
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@db4aacadf4db71778afb0c8a452382184a71d318
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: gatsby build --prefix-paths
        CNAME: noahgilmore.com
